import { defineConfig } from "vitest/config";

export default defineConfig({
    test: {
        include: [
            "crucible/__tests__/domain-canonical.test.mjs",
            "crucible/__tests__/domain-enumerands.test.mjs",
            "crucible/__tests__/domain-hypotheses.test.mjs",
            "crucible/__tests__/domain-statistics.test.mjs",
            "crucible/__tests__/domain-cohort.test.mjs",
            "crucible/__tests__/domain-confirmation-protocol.test.mjs",
            "crucible/__tests__/domain-archive-strategy.test.mjs",
            "crucible/__tests__/domain-working-set-policy.test.mjs",
            "crucible/__tests__/domain-kernel.test.mjs",
            "crucible/__tests__/v4-stat-contract.test.mjs",
            "crucible/__tests__/measurement-parser.test.mjs",
            "crucible/__tests__/measurement-verifier-parser.test.mjs",
            "crucible/__tests__/measurement-harness-suite.test.mjs",
            "crucible/__tests__/runtime-identity.test.mjs",
            "crucible/__tests__/runtime-resource-broker.test.mjs",
            "crucible/__tests__/persistence-recovery-catalog.test.mjs",
            "crucible/__tests__/persistence-retention.test.mjs",
            "crucible/__tests__/runtime-discovery.test.mjs",
            "crucible/__tests__/runtime-recovery-daemon.test.mjs",
            "crucible/__tests__/runtime-recovery-cli.test.mjs",
            "crucible/__tests__/runtime-process-identity.test.mjs",
            "crucible/__tests__/runtime-prediction-feedback.test.mjs",
            "crucible/__tests__/runtime-sdk-availability.test.mjs",
            "crucible/__tests__/release-plumbing.test.mjs",
            "crucible/__tests__/tools-recovery-task.test.mjs",
            "crucible/__tests__/api-schema.test.mjs",
            "crucible/__tests__/api-lifecycle.test.mjs",
            "crucible/__tests__/api-handlers.test.mjs",
        ],
        testTimeout: 10_000,
        hookTimeout: 10_000,
    },
});
